In [1]:
import torch
import numpy as np

x = np.array([2,3,4])
y = np.power(x,1)
y

print(torch.zeros(1)) 

tensor([0.])


In [14]:
import numpy as np
import torch

torch.manual_seed(0)
X = torch.rand((10,4))
w = torch.rand((4,3))
b = torch.ones((1,3))

print(w)
print(b)
print(w+b)

(X @ w) + b, X @ (w + b) 

tensor([[0.5263, 0.2437, 0.5846],
        [0.0332, 0.1387, 0.2422],
        [0.8155, 0.7932, 0.2783],
        [0.4820, 0.8198, 0.9971]])
tensor([[1., 1., 1.]])
tensor([[1.5263, 1.2437, 1.5846],
        [1.0332, 1.1387, 1.2422],
        [1.8155, 1.7932, 1.2783],
        [1.4820, 1.8198, 1.9971]])


(tensor([[1.4224, 1.4059, 1.6325],
         [2.0145, 2.2865, 2.3635],
         [1.7389, 1.8048, 1.9171],
         [1.5069, 1.6870, 1.6527],
         [1.6611, 1.6401, 1.9279],
         [2.1342, 2.3246, 2.6022],
         [2.0334, 1.9642, 1.6803],
         [1.8079, 2.1030, 2.2129],
         [1.2397, 1.2258, 1.2418],
         [2.0878, 2.3618, 2.2883]]),
 tensor([[1.9074, 1.8909, 2.1174],
         [3.3426, 3.6145, 3.6915],
         [2.5774, 2.6433, 2.7557],
         [1.5105, 1.6906, 1.6563],
         [2.6020, 2.5811, 2.8689],
         [4.0023, 4.1927, 4.4703],
         [2.9946, 2.9254, 2.6415],
         [2.6036, 2.8987, 3.0086],
         [0.8678, 0.8540, 0.8699],
         [3.6912, 3.9652, 3.8916]]))

In [18]:
import numpy as np
import torch

torch.manual_seed(0)
X = torch.rand((4,3)) + torch.rand((4,3)) + torch.rand((4,3))
expx = torch.exp(X)
print(X)
print(expx)
partition = expx.sum(dim = 1, keepdim = True)
softmax = expx / partition

tensor([[0.9380, 1.4900, 1.3351],
        [0.6867, 1.1903, 1.8075],
        [0.9562, 2.1107, 1.3131],
        [1.8173, 0.8967, 1.3076]])
tensor([[2.5548, 4.4370, 3.8004],
        [1.9872, 3.2881, 6.0952],
        [2.6019, 8.2541, 3.7179],
        [6.1554, 2.4514, 3.6973]])


tensor([1.0000, 1.0000, 1.0000, 1.0000])