# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
t = torch.rand(7,7)
t

tensor([[0.7839, 0.3504, 0.8365, 0.5521, 0.9937, 0.3407, 0.0487],
        [0.9703, 0.8350, 0.3655, 0.6484, 0.3577, 0.8675, 0.9978],
        [0.5195, 0.8891, 0.3633, 0.2258, 0.9733, 0.3169, 0.2586],
        [0.5800, 0.7542, 0.0168, 0.7849, 0.4761, 0.4966, 0.8578],
        [0.4721, 0.2023, 0.5984, 0.9684, 0.2947, 0.4834, 0.0961],
        [0.1672, 0.5670, 0.3357, 0.3097, 0.7003, 0.0805, 0.3447],
        [0.3122, 0.5937, 0.3766, 0.2178, 0.7838, 0.1847, 0.1752]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [17]:
# Create another random tensor
t2 = torch.rand(1,7)
print(t2.shape)
t2 = t2.reshape(7,1)
print(t2.shape)

# Perform matrix multiplication 
t @ t2

torch.Size([1, 7])
torch.Size([7, 1])


tensor([[1.8285],
        [2.3143],
        [1.7701],
        [1.6975],
        [1.1392],
        [1.1899],
        [1.2952]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed


# Create two random tensors


# Matrix multiply tensors


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed


# Check for access to GPU

# Create two random tensors on GPU



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
