# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
t = torch.rand(7,7)
t

tensor([[0.7885, 0.6889, 0.4535, 0.5935, 0.8212, 0.4030, 0.7217],
        [0.9026, 0.4688, 0.7374, 0.8993, 0.2759, 0.7384, 0.4712],
        [0.1884, 0.9137, 0.9733, 0.5103, 0.4542, 0.4571, 0.3896],
        [0.5012, 0.7302, 0.1919, 0.3149, 0.8341, 0.3501, 0.6174],
        [0.2743, 0.0069, 0.1524, 0.1915, 0.7478, 0.5172, 0.1293],
        [0.9589, 0.5640, 0.0707, 0.2519, 0.1930, 0.5913, 0.8089],
        [0.7608, 0.6649, 0.2003, 0.9157, 0.8186, 0.3374, 0.7912]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
t2 = torch.rand(1,7)
print(t2.shape)
t2 = t2.reshape(7,1)
print(t2.shape)

# Perform matrix multiplication 
t @ t2

torch.Size([1, 7])
torch.Size([7, 1])


tensor([[1.2063],
        [1.2509],
        [1.2222],
        [1.0242],
        [0.4883],
        [1.0581],
        [1.1427]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Create another random tensor
t2 = torch.rand(1,7)
print(t2.shape)
t2 = t2.reshape(7,1)
print(t2.shape)

# Perform matrix multiplication 
torch.matmul(t,t2)


torch.Size([1, 7])
torch.Size([7, 1])


tensor([[2.2459],
        [2.2675],
        [1.9720],
        [1.6581],
        [0.7684],
        [1.7812],
        [2.0859]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [33]:
# Check for access to GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

torch.__version__

# Create two random tensors on GPU
t1 = torch.rand(2,3).to(device)
t2 = torch.rand(2,3).to(device)

t1,t2


Using device: cuda


(tensor([[0.7625, 0.9472, 0.7613],
         [0.6065, 0.7175, 0.6052]], device='cuda:0'),
 tensor([[0.1762, 0.4774, 0.4996],
         [0.1888, 0.0132, 0.4077]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [34]:
# Perform matmul on tensor_A and tensor_B
T = torch.matmul(t1, t2.T)
T


tensor([[0.9668, 0.4669],
        [0.7517, 0.3707]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [35]:
# Find max
print(torch.max(T))

# Find min
print(torch.min(T))


tensor(0.9668, device='cuda:0')
tensor(0.3707, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [36]:
# Find arg max
print(torch.argmax(T)) #argmax treats the tensor as if it were flattened

# Find arg min
print(torch.argmin(T))

tensor(0, device='cuda:0')
tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.manual_seed(7)

# Create random tensor
t = torch.rand(size=(1,1,1,10))

# Remove single dimensions

#t = t.squeeze(0)
#t = t.squeeze(0)
#t = t.squeeze(0)
#OR
t = t.squeeze()

t

# Print out tensors and their shapes


tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])