# Tensors
[Torch docs on tensors](https://pytorch.org/docs/stable/tensors.html) 

In [88]:
import torch
import numpy as np
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
print('Using device:', device)

torch.__version__

Using device: cpu


'1.12.0+cu102'

## Creating Tensors  
From a python list

In [89]:
torch.tensor([[2 , 3],[4 , 5]])

tensor([[2, 3],
        [4, 5]])

From a numpy array

In [90]:
v = np.array([[[1,2],[2,3],[4,5]]])
t = torch.tensor(v)

From random values

In [91]:
torch.rand(size=(1,3,3))

tensor([[[0.2077, 0.3063, 0.0585],
         [0.8314, 0.4566, 0.8445],
         [0.6883, 0.4008, 0.1803]]])

In a range of values

In [92]:
torch.arange(0,10,1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

[Torch docs on how to create tensors](https://pytorch.org/docs/stable/torch.html#tensor-creation-ops)

## Tensor attributes
[Docs on tensor attributes](https://pytorch.org/docs/stable/tensor_attributes.html#tensor-attributes-doc)

In [122]:
v = np.array([[[1,2],[2,3],[4,5]]])
t = torch.tensor(v)
t.ndim #3 dimensions
t.shape #1 dimension of 3x2 matrices (always from out to in and row first)
t.device
t.dtype

t = t.type(torch.float16) #changing datatype of the tensor
t

3

torch.Size([1, 3, 2])

device(type='cpu')

torch.int64

tensor([[[1., 2.],
         [2., 3.],
         [4., 5.]]], dtype=torch.float16)

## Tensor manipulation

Applying a linear transformation to the incoming data:  $ y = x A^T + b $

In [99]:
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]], dtype=torch.float32)
# Since the linear layer starts with a random weights matrix A, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
x = x.T
linear = torch.nn.Linear(in_features=3, # in_features = matches inner dimension of input (second index of x, aka its columns)
                         out_features=4, # out_features = describes outer value (second index of A, aka its columns)
                         bias = True)
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([2, 3])

Output:
tensor([[1.6293, 0.8116, 3.5593, 1.5407],
        [2.4146, 1.3319, 4.1262, 1.7270]], grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 4])


Aggregating tensors

In [116]:
v = torch.arange(0, 100, 10)
v
print(f"Maximum {torch.max(v)} at index {torch.argmax(v)}")
print(f"Minimum {torch.min(v)} at index {torch.argmin(v)}")
print(f"Mean: {torch.mean(v.type(torch.float32))}")
print(f"Sum: {torch.sum(v)}")


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Maximum 90 at index 9
Minimum 0 at index 0
Mean: 45.0
Sum: 450
